data:extend({
   {
      type = "string-setting",
      name = "ZRecycling-recoveryrate",
      setting_type = "startup",
      default_value = "1",
	  allowed_values = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }, 
      order = "ba",
   },
   {
      type = "string-setting",
      name = "ZRecycling-recoveryspeed",
      setting_type = "startup",
      default_value = "=",
	  allowed_values = { "=", "1/2", "1/3", "1/4" }, 
      order = "ba",
   },
   {
      type = "string-setting",
      name = "ZRecycling-difficulty",
      setting_type = "startup",
      default_value = "Expensive",
	  allowed_values = { "Expensive", "Normal" }, 
      order = "ba",
   },
   -- For future version --
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-storage",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "a",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-belt",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "b",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-inserter",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "c",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-energy-pipe-distribution",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "d",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-transport",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "e",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-logistic-network",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "f",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-circuit-network",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "g",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-tool",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "h",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-energy",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "i",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-extraction-machine",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "j",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-smelting-machine",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "k",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-production-machine",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "l",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-module",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "m",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-recycling-machine",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "ma",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-gun",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "n",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-ammo",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "o",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-capsule",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "p",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-armor",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "q",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-equipment",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "r",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-defensive-structure",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "s",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-intermediate-product",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "mt",
   -- },
   -- {
   -- type = "bool-setting",
   -- name = "ZRecycling-science-pack",
   -- setting_type = "runtime-global",
   -- default_value = true,
   -- order = "mu",
   -- },
})